apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trash-levels.fullname" . }}
  labels:
    {{- include "trash-levels.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "trash-levels.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "trash-levels.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          ports:
          - containerPort: 8080
