{{- if .Values.ingress.enabled -}}
{{- $fullName := include "trash-levels.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "trash-levels.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: ambassador
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
  {{- end }}
{{- end }}
