apiVersion: apps/v1
kind: Deployment
metadata:
  name: trash-levels
  labels:
    app: trash-levels
    project: cicd-demo
    vender: rx-m
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trash-levels
  template:
    metadata:
      labels:
        app: trash-levels
    spec:
      containers:
      - name: trash-levels
        image: rxmllc/trash-levels
        ports:
        - containerPort: 8080
